# Generated by Django 3.2.9 on 2021-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20211117_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Blog/images')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.TextField(choices=[('blog_post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MarketingFeature/images')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product/images')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='Product/logos')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Testimonial/images')),
                ('logo', models.FileField(upload_to='Testimonial/logos')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('designation', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='VideoBlog/images')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='VideoBlog/logos')),
            ],
        ),
    ]
