# Generated by Django 3.2.9 on 2021-11-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_blog_marketingfeature_product_testimonial_videoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_redirection',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
