# Generated by Django 3.2.9 on 2021-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_marketingfeature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
