# Generated by Django 3.2.9 on 2021-11-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20211118_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id']},
        ),
    ]
