# Generated by Django 3.2.9 on 2021-11-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_testimonial_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bg',
        ),
    ]
