# Generated by Django 3.2.9 on 2021-11-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='white_logo',
            field=models.FileField(blank=True, null=True, upload_to='Customer/'),
        ),
    ]
