# Generated by Django 3.2.9 on 2021-11-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_customer_white_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.FileField(default='Ah', upload_to='Product/hero-images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
