# Generated by Django 3.2.9 on 2021-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20211122_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(default='#ffc9b7', max_length=255),
            preserve_default=False,
        ),
    ]
